//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.EMP_CLIENTE = new HashSet<EMP_CLIENTE>();
        }
    
        public decimal ID_CLI { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string CORREO { get; set; }
        public string RUT { get; set; }
        public string UBICACION { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<decimal> PERFIL_ID_PERFIL { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_CLIENTE> EMP_CLIENTE { get; set; }
    }
}
