//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_RESERVA
    {
        public decimal ID_DETALLE { get; set; }
        public decimal COD_CLI { get; set; }
        public Nullable<decimal> HABITACION_ID_HABIT { get; set; }
        public decimal RESERVA_ID_RESERVA { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
