//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_HOSTAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_HOSTAL()
        {
            this.O_COMPRA = new HashSet<O_COMPRA>();
        }
    
        public decimal COD_EMP { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public string CORREO { get; set; }
        public string RUN { get; set; }
        public string TELEFONO { get; set; }
        public decimal PERFIL_ID_PERFIL { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_COMPRA> O_COMPRA { get; set; }
    }
}
