//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public decimal ID_FACTURA { get; set; }
        public System.DateTime FECHA_FACTURA { get; set; }
        public decimal TOTAL_PAGAR { get; set; }
        public Nullable<decimal> RESERVA_ID_RESERVA { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
    }
}
