//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public decimal ID_MENU { get; set; }
        public string NOMBRE { get; set; }
        public string CONTENIDO { get; set; }
        public decimal PRECIO { get; set; }
        public decimal COMEDOR_ID_SERVICIO { get; set; }
    
        public virtual COMEDOR COMEDOR { get; set; }
    }
}
