//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public O_COMPRA()
        {
            this.DETALLE_O_COMPRA = new HashSet<DETALLE_O_COMPRA>();
        }
    
        public decimal ID_ORDEN { get; set; }
        public System.DateTime FECHA_ORDEN { get; set; }
        public decimal TOTAL { get; set; }
        public string ESTADO_ORDEN { get; set; }
        public Nullable<decimal> EMP_HOSTAL_COD_EMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_O_COMPRA> DETALLE_O_COMPRA { get; set; }
        public virtual EMP_HOSTAL EMP_HOSTAL { get; set; }
    }
}
