//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE_O_COMPRA = new HashSet<DETALLE_O_COMPRA>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public Nullable<decimal> PROVEEDOR_ID_PROVEEDOR { get; set; }
        public decimal CANT_STOCK { get; set; }
        public decimal STOCK_CRITICO { get; set; }
        public Nullable<decimal> CATEGORIA_ID_CATEGORIA { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_O_COMPRA> DETALLE_O_COMPRA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
