//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.D_RESERVA = new HashSet<D_RESERVA>();
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public decimal ID_RESERVA { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_ENTRADA { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public decimal CANT_DIAS { get; set; }
        public Nullable<decimal> ID_CLI { get; set; }
        public string ESTADO { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<decimal> COMEDOR_ID_SERVICIO { get; set; }
    
        public virtual COMEDOR COMEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_RESERVA> D_RESERVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
